### ISSUE TITLE
Support namespace in gradle

### ISSUE THREAD

**Issue by michelesacc** [OutdatedGuy/package_rename#20]
The new gradle plugin now adds the namespace in the app's gradle file.

Can we please add support for rename this:

`if (project.android.hasProperty("namespace")) {
    namespace 'com.app.bundle.to.rename'
}`

https://developer.android.com/build/configure-app-module#groovy

**Comment by OutdatedGuy** [comment]
Changing `namespace` is supported starting from version `v1.3.0` of this plugin. Can you try upgrading your package to this or the later versions and check again.

Also I noticed a bug in package that prevents `namespace` update if the value is surrounded in a single quotes `'` instead of double quotes `"`.

> if (project.android.hasProperty("namespace")) { namespace 'com.app.bundle.to.rename' }

Try upgrading namespace to `namespace "com.app.bundle.to.rename"` and then try running the package.

I'll publish a new release to make the package quotes insensitive.
